server:
  port: 8080

spring:
  application:
    name: authuser

  datasource:
    url: jdbc:postgresql://localhost:5433/ead-authuser
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
